index:
    path: /
    controller: App\Controller\DefaultController::index

app_register:
    path: /register
    controller: App\Controller\SecurityController::register

createUser:
    path: /createUser
    controller: App\Controller\SecurityController::createUser