index:
    path: /
    controller: App\Controller\DefaultController::index

app_register:
    path: /register
    controller: App\Controller\SecurityController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

createUser:
    path: /createUser
    controller: App\Controller\SecurityController::createUser